/// Flutter icons IconSvg
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IconSvg
///      fonts:
///       - asset: fonts/IconSvg.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class IconSvg {
  IconSvg._();

  static const _kFontFam = 'IconSvg';
  static const _kFontPkg = null;

  static const IconData search = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData web = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData whatsapp = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instagram = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
